/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/planejamento': typeof PlanejamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/planejamento': typeof PlanejamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cronograma': typeof CronogramaRoute
  '/planejamento': typeof PlanejamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cronograma' | '/planejamento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cronograma' | '/planejamento'
  id: '__root__' | '/' | '/cronograma' | '/planejamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronogramaRoute: typeof CronogramaRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronogramaRoute: CronogramaRoute,
  PlanejamentoRoute: PlanejamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
